### ISSUE TITLE
Unable to load svg or pngs when using React Component - 404 trying to get file from https://www.ebi.ac.uk/gxa/[id].png

### ISSUE THREAD

**Issue by andiamantoukos-fadv** [gxa/anatomogram#15]
Hi! I am working on importing the Anatomogram directly as a React component.
The JSX is pretty bare-bones as I am just starting out getting it to display similar to the demo site:

```
<Anatomogram species={'homo_sapiens'} onMouseOver={() => {}} onClick={() => {}} onMouseOut={() => {}} />
```

When I load this in the browser, it is unable to load the image files - The 4 requests it makes are:

* https://www.ebi.ac.uk/gxa/fe374fbbda778cc8600ca3d2bbf49074.png
* https://www.ebi.ac.uk/gxa/269274763eff686d3c27aece90a0c026.png
* https://www.ebi.ac.uk/gxa/bc6cb140072af5b41e6dc150228f8735.png
* https://www.ebi.ac.uk/gxa/4626c730027e5ff70254d23451537f9a.svg

Is there some extra setup step I need to correctly use the files either on the ebi site or that are in the npm module?

[Here](https://github.com/cBioCenter/chell-viz/blob/master/webpack.chell-common.ts) is the webpack 4 configuration for my repo - I am unsure if it is interfering, but this is probably the most relevant stanza:

```
module: {
    rules: [
      ...,
      {
        test: /\.(woff(2)?|ttf|png|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'fonts/',
            },
          },
        ],
      },
    ],
  },
}
```

I have tried fiddling with these settings to either load svg/png the same way what is being used in the example Anatomogram site and in the [the heatmap repo](https://github.com/ebi-gene-expression-group/atlas-heatmap), changing/removing the outputpath, as well as just taking the loader out of my config altogether.

The only other result I have gotten so far is getting the IDs to be renamed - For example, `https://www.ebi.ac.uk/gxa/4626c730027e5ff70254d23451537f9a.svg` becomes `https://www.ebi.ac.uk/gxa/fonts/homo_sapiens.male.svg`.

Any further help would be greatly appreciated, thanks!

**Comment by alfonsomunozpomer** [comment]
Hi Drew,

The prop `atlasUrl` defaults to `https://www.ebi.ac.uk/gxa/` which might in principle be ok, but it turns out that the prop name is quite misleading, especially if you want to build the component yourself. Think of `atlasUrl` as the base domain where you’re hosting the static assets (SVGs and PNGs).

I think that what you want is to set `atlasUrl` to an empty string:
```
<Anatomogram atlasUrl={``} ... />
```
Then all files will be resolved against `localhost` and whatever’s set in Webpack’s server `publicPath` (`/dist/` if you haven’t changed it). In that way, the four requests will be like:
```
/dist/fe374fbbda778cc8600ca3d2bbf49074.png
```
Which will load the assets correctly.

I’d like to rename `atlasUrl` to `baseUrl` so that it’s not misleading about what it serves and also update the component to official Webpack 4, WDS 3 and Babel 7. I hope I can find some time next week to give it a bump.

Please let me know if the above makes sense and if it’s helpful. May I know what sort of app are you integrating the Anatomogram into?

**Comment by andiamantoukos-fadv** [comment]
Ah-ha! Yep, that was definitely the lead I needed, thank you - closing issue as resolved!

Looks like a webpack loader is required, in that completely removing my `file-loader` (understandably) throws errors. The flipside is the loaders can be configured to, for example, put the anatomogram assets in their own directory which is great.

I'm not familiar with `image-webpack-loader`, would you say it's required or would I get by with just the `file-loader` for the svg/pngs?

I'm currently working on integrating Anatomogram as a visualization for [this library](https://github.com/cBioCenter/chell-viz) as part of the Human Cell Atlas!  😃

**Comment by alfonsomunozpomer** [comment]
SVGs are XMLs and you should just use `file-loader`, but PNGs are re-processed (optimized and compressed) by `image-webpack-loader` which can be helpful, although due to the size of the images it’s not going to get you very far, other than shaving off a few bytes. In any case I think it’s good practice, especially renaming them using a hash, which ensures that if the file doesn’t change it can be cached (but yes, `file-loader` gives you that as well).

Glad you got it working!
